version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 🔥 FIXED LISTENERS
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: finstream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark

    container_name: spark

    command: ["sleep", "infinity"]

    ports:
      - "8080:8080"

    volumes:
      - ../:/app

    working_dir: /app

    environment:
      - KAFKA_BOOTSTRAP=kafka:29092
      - KAFKA_TOPIC=transactions

      - POSTGRES_URL=jdbc:postgresql://postgres:5432/finstream
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_TABLE=transactions

      - SNOWFLAKE_ACCOUNT=qa85237.ap-southeast-7.aws
      - SNOWFLAKE_USER=yalamelivishal55
      - SNOWFLAKE_PASSWORD=Vishal$1234

      - SNOWFLAKE_WAREHOUSE=COMPUTE_WH
      - SNOWFLAKE_DATABASE=FINSTREAM_DB
      - SNOWFLAKE_SCHEMA=PUBLIC
      - SNOWFLAKE_TABLE=TRANSACTIONS

    depends_on:
      - kafka
      - postgres
 
  